# Generated by Django 6.0.4 on 2026-04-14 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_format', models.CharField(choices=[('is', 'YYYY-MM-DD'), ('ed', 'DD.MM.YYYY'), ('es', 'DD/MM/YYYY'), ('us', 'MM/DD/YYYY'), ('dt', 'YYYY.MM.DD'), ('cp', 'YYYYMMDD')], default='is', max_length=2)),
                ('decimal_format', models.CharField(choices=[('us', '1,234,567.8'), ('eu', '1 234 567,8'), ('de', '1.234.567,8'), ('nn', '1234567.8'), ('ch', "1'234'567.8")], default='us', max_length=2)),
                ('time_zone', models.CharField(default='Etc/UTC', max_length=64)),
                ('time_format', models.CharField(choices=[('12', '12-hour'), ('24', '24-hour')], default='24', max_length=2)),
                ('fiori_theme', models.CharField(choices=[('sap_horizon', 'Morning Horizon (Light)'), ('sap_horizon_dark', 'Evening Horizon (Dark)'), ('sap_horizon_hcb', 'Horizon High Contrast Black'), ('sap_horizon_hcw', 'Horizon High Contrast White'), ('sap_horizon_auto', 'OS Adaptive Horizon Theme'), ('sap_horizon_hc_auto', 'OS Adaptive Hight Contrast Horizon Theme'), ('sap_fiori_3', 'Quartz Light'), ('sap_fiori_3_dark', 'Quartz Dark'), ('sap_fiori_3_hcb', 'Quartz High Contrast Black'), ('sap_fiori_3_hcw', 'Quartz High Contrast White')], default='sap_horizon_auto', max_length=19)),
                ('show_timezone', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
