# Generated by Django 6.0.4 on 2026-04-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userpreferences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'permissions': [('manage_user_groups', 'Can manage the groups of a user'), ('manage_group_permissions', 'Can manage the permissions of a group')]},
        ),
    ]
