# Generated by Django 6.0.4 on 2026-04-24 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('query_parameter', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('is_visible_by_default', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Filter Definition',
                'verbose_name_plural': 'Filter Definitions',
                'constraints': [models.UniqueConstraint(fields=('table_id', 'name'), name='unique_table_filter_definition')],
            },
        ),
        migrations.CreateModel(
            name='FilterVariant',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, max_length=120, null=True)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('exclude_filters', models.JSONField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('execute_on_selection', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_variants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filter Variant',
                'verbose_name_plural': 'Filter Variants',
            },
        ),
        migrations.CreateModel(
            name='UserColumnPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('expression', models.JSONField(default=dict)),
                ('label', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Column Preferences',
                'verbose_name_plural': 'User Column Preferences',
                'ordering': ['user', 'table_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserDefaultFilterVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_variants', to='ui_preferences.filtervariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_filter_variants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Default Filter Variant',
                'verbose_name_plural': 'User Default Filter Variants',
            },
        ),
        migrations.CreateModel(
            name='UserFilterPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('filter_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='ui_preferences.filterdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Filter Preferences',
                'verbose_name_plural': 'User Filter Preferences',
            },
        ),
        migrations.AddConstraint(
            model_name='filtervariant',
            constraint=models.UniqueConstraint(fields=('table_id', 'name', 'created_by'), name='unique_variant_per_user'),
        ),
        migrations.AddConstraint(
            model_name='filtervariant',
            constraint=models.UniqueConstraint(fields=('table_id', 'slug', 'created_by'), name='unique_slug_per_user'),
        ),
        migrations.AddConstraint(
            model_name='usercolumnpreference',
            constraint=models.UniqueConstraint(fields=('user', 'table_id', 'key'), name='unique_user_table_column_preference'),
        ),
        migrations.AddConstraint(
            model_name='userfilterpreference',
            constraint=models.UniqueConstraint(fields=('user', 'filter_definition'), name='unique_user_filter_definition_preference'),
        ),
    ]
